#pragma once

// ============================================================
// FakePod 统一诊断档位
// ============================================================
// RELEASE：正式运行，关闭高频性能/交互 Trace，仅保留生命周期关键点与 W/E。
// DEBUG：  增加启动细节与用户交互 Trace。
// STRESS： 打开性能审计、Transport/Launcher 统计及既有专项诊断。
//
// 任一 APP_DIAG_xxx 仍可由 PlatformIO 单独 -D 覆盖，保持专项回归兼容。

#define APP_DIAG_PROFILE_RELEASE 0
#define APP_DIAG_PROFILE_DEBUG   1
#define APP_DIAG_PROFILE_STRESS  2

// 关闭诊断日志时仍让编译器“看到”日志参数，避免仅用于日志的局部变量/辅助函数
// 在 RELEASE 下触发 -Wunused-variable / -Wunused-function。常量 false 分支不会执行，
// 因此计时、heap 查询等日志参数也不会产生运行期开销。
#define APP_DIAG_DISCARDED_LOGI(tag, ...) \
    do { if (0) { ESP_LOGI((tag), __VA_ARGS__); } } while (0)

#ifndef APP_DIAG_PROFILE
#define APP_DIAG_PROFILE APP_DIAG_PROFILE_RELEASE
#endif

#if APP_DIAG_PROFILE < APP_DIAG_PROFILE_RELEASE || APP_DIAG_PROFILE > APP_DIAG_PROFILE_STRESS
#error "APP_DIAG_PROFILE must be RELEASE(0), DEBUG(1), or STRESS(2)"
#endif

#if APP_DIAG_PROFILE == APP_DIAG_PROFILE_RELEASE
#define APP_DIAG_PROFILE_NAME "RELEASE"
#elif APP_DIAG_PROFILE == APP_DIAG_PROFILE_DEBUG
#define APP_DIAG_PROFILE_NAME "DEBUG"
#else
#define APP_DIAG_PROFILE_NAME "STRESS"
#endif

// 启动说明/正常交互属于 DEBUG；逐帧性能与底层 Transport 属于 STRESS。
#ifndef APP_DIAG_BOOT_VERBOSE
#define APP_DIAG_BOOT_VERBOSE (APP_DIAG_PROFILE >= APP_DIAG_PROFILE_DEBUG)
#endif

#ifndef APP_DIAG_UI_INTERACTION
#define APP_DIAG_UI_INTERACTION (APP_DIAG_PROFILE >= APP_DIAG_PROFILE_DEBUG)
#endif

#ifndef APP_DIAG_UI_PERFORMANCE
#define APP_DIAG_UI_PERFORMANCE (APP_DIAG_PROFILE >= APP_DIAG_PROFILE_STRESS)
#endif

#ifndef APP_DIAG_LAUNCHER_PERFORMANCE
#define APP_DIAG_LAUNCHER_PERFORMANCE (APP_DIAG_PROFILE >= APP_DIAG_PROFILE_STRESS)
#endif

#ifndef APP_DIAG_DISPLAY_TRANSPORT
#define APP_DIAG_DISPLAY_TRANSPORT (APP_DIAG_PROFILE >= APP_DIAG_PROFILE_STRESS)
#endif

// 既有专项诊断默认只在 STRESS 打开；仍允许单项 -DAPP_DIAG_xxx=1 覆盖。
#ifndef APP_DIAG_AUDIO_RAM
#define APP_DIAG_AUDIO_RAM (APP_DIAG_PROFILE >= APP_DIAG_PROFILE_STRESS)
#endif
#ifndef APP_DIAG_AUDIO_POP
#define APP_DIAG_AUDIO_POP (APP_DIAG_PROFILE >= APP_DIAG_PROFILE_STRESS)
#endif
#ifndef APP_DIAG_AUDIO_CLOCK
#define APP_DIAG_AUDIO_CLOCK (APP_DIAG_PROFILE >= APP_DIAG_PROFILE_STRESS)
#endif
#ifndef APP_DIAG_AUDIO_SOURCE
#define APP_DIAG_AUDIO_SOURCE (APP_DIAG_PROFILE >= APP_DIAG_PROFILE_STRESS)
#endif
#ifndef APP_DIAG_AUDIO_INDEX
#define APP_DIAG_AUDIO_INDEX (APP_DIAG_PROFILE >= APP_DIAG_PROFILE_STRESS)
#endif
#ifndef APP_DIAG_AUDIO_WORKSPACE
#define APP_DIAG_AUDIO_WORKSPACE (APP_DIAG_PROFILE >= APP_DIAG_PROFILE_STRESS)
#endif
#ifndef APP_DIAG_TRANSPORT_INTENT
#define APP_DIAG_TRANSPORT_INTENT (APP_DIAG_PROFILE >= APP_DIAG_PROFILE_STRESS)
#endif
#ifndef APP_DIAG_AUDIO_SEEK
#define APP_DIAG_AUDIO_SEEK (APP_DIAG_PROFILE >= APP_DIAG_PROFILE_STRESS)
#endif
#ifndef APP_DIAG_AUDIO_CODEC
#define APP_DIAG_AUDIO_CODEC (APP_DIAG_PROFILE >= APP_DIAG_PROFILE_STRESS)
#endif
#ifndef APP_DIAG_LIBRARY_METADATA
#define APP_DIAG_LIBRARY_METADATA (APP_DIAG_PROFILE >= APP_DIAG_PROFILE_STRESS)
#endif
#ifndef APP_DIAG_LIBRARY_ITEMS
#define APP_DIAG_LIBRARY_ITEMS (APP_DIAG_PROFILE >= APP_DIAG_PROFILE_STRESS)
#endif
#ifndef APP_DIAG_LIBRARY_ARTWORK
#define APP_DIAG_LIBRARY_ARTWORK (APP_DIAG_PROFILE >= APP_DIAG_PROFILE_STRESS)
#endif
#ifndef APP_DIAG_ARTWORK_LOADER
#define APP_DIAG_ARTWORK_LOADER (APP_DIAG_PROFILE >= APP_DIAG_PROFILE_STRESS)
#endif
#ifndef APP_DIAG_ARTWORK_UI
#define APP_DIAG_ARTWORK_UI (APP_DIAG_PROFILE >= APP_DIAG_PROFILE_STRESS)
#endif
#ifndef APP_DIAG_SYSTEM_HEARTBEAT
#define APP_DIAG_SYSTEM_HEARTBEAT (APP_DIAG_PROFILE >= APP_DIAG_PROFILE_STRESS)
#endif
#ifndef APP_DIAG_PLAYER_PLAYLIST
#define APP_DIAG_PLAYER_PLAYLIST (APP_DIAG_PROFILE >= APP_DIAG_PROFILE_STRESS)
#endif
#ifndef APP_DIAG_PLAYER_TRANSPORT
#define APP_DIAG_PLAYER_TRANSPORT (APP_DIAG_PROFILE >= APP_DIAG_PROFILE_STRESS)
#endif
#ifndef APP_DIAG_FLAC_PERFORMANCE
#define APP_DIAG_FLAC_PERFORMANCE (APP_DIAG_PROFILE >= APP_DIAG_PROFILE_STRESS)
#endif
#ifndef APP_DIAG_MP3_PERFORMANCE
#define APP_DIAG_MP3_PERFORMANCE (APP_DIAG_PROFILE >= APP_DIAG_PROFILE_STRESS)
#endif
